# Generated by Django 6.0.3 on 2026-03-07 17:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('pid', models.IntegerField(help_text='Process ID')),
                ('name', models.CharField(help_text='Process name', max_length=255)),
                ('cpu_percent', models.FloatField(help_text='CPU usage percentage')),
                ('memory_percent', models.FloatField(help_text='Memory usage percentage')),
                ('status', models.CharField(help_text='Process status', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Process Information',
                'ordering': ['-cpu_percent'],
            },
        ),
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('cpu_percent', models.FloatField(help_text='Overall CPU usage percentage')),
                ('cpu_temp', models.FloatField(blank=True, help_text='CPU temperature in Celsius', null=True)),
                ('cpu_freq', models.FloatField(blank=True, help_text='CPU frequency in MHz', null=True)),
                ('memory_percent', models.FloatField(help_text='RAM usage percentage')),
                ('memory_used', models.BigIntegerField(help_text='Used memory in bytes')),
                ('memory_total', models.BigIntegerField(help_text='Total memory in bytes')),
                ('swap_percent', models.FloatField(help_text='Swap usage percentage')),
                ('swap_used', models.BigIntegerField(help_text='Used swap in bytes')),
                ('swap_total', models.BigIntegerField(help_text='Total swap in bytes')),
                ('disk_percent', models.FloatField(help_text='Disk usage percentage')),
                ('disk_used', models.BigIntegerField(help_text='Used disk space in bytes')),
                ('disk_total', models.BigIntegerField(help_text='Total disk space in bytes')),
                ('network_bytes_sent', models.BigIntegerField(help_text='Total bytes sent')),
                ('network_bytes_recv', models.BigIntegerField(help_text='Total bytes received')),
                ('fan_speed', models.IntegerField(blank=True, help_text='Fan speed in RPM', null=True)),
            ],
            options={
                'verbose_name_plural': 'System Metrics',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='raspberry_p_timesta_1ab1db_idx')],
            },
        ),
    ]
