# Generated by Django 6.0.3 on 2026-04-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raspberry_pi_htop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemmetrics',
            name='packets_dropped_in',
            field=models.BigIntegerField(default=0, help_text='Total inbound packets dropped'),
        ),
        migrations.AddField(
            model_name='systemmetrics',
            name='packets_dropped_out',
            field=models.BigIntegerField(default=0, help_text='Total outbound packets dropped'),
        ),
    ]
