# Generated by Django 6.0.3 on 2026-09-28 16:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raspberry_pi_htop', '0002_systemmetrics_packets_dropped_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemmetrics',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
